const UsuarioConstants = {
    REQUEST: 'REQUEST',
    FAILURE: 'FAILURE',
    SUCCESS: 'SUCCESS',
    GET_USUARIOS_SUCCESS: 'GET_USUARIOS_SUCCESS',
    GET_ROL_AC_SUCCESS: 'GET_ROL_AC_SUCCESS',
    GET_PRF_AC_SUCCESS: 'GET_PRF_AC_SUCCESS',
    GET_FICHA_USER_SUCCESS: 'GET_FICHA_USER_SUCCESS',
};

const TicketConstants = {
    TCKT_REQUEST: 'TCKT_REQUEST',
    TCKT_FAILURE: 'TCKT_FAILURE',
    TCKT_SUCCESS: 'TCKT_SUCCESS',
    GET_CTGR_TCKT_SUCCESS: 'GET_CTGR_TCKT_SUCCESS',
    GET_TCKT_CTGR_SUCCESS: 'GET_TCKT_CTGR_SUCCESS',
    GET_PTGS_SUCCESS: 'GET_PTGS_SUCCESS',
    GET_PTGS_ACT_SUCCESS: 'GET_PTGS_ACT_SUCCESS'
};

export {
    UsuarioConstants,
    TicketConstants
}