const UsuarioConstants = {
    REQUEST: 'REQUEST',
    FAILURE: 'FAILURE',
    SUCCESS: 'SUCCESS',
    GET_USUARIOS_SUCCESS: 'GET_USUARIOS_SUCCESS',
    GET_ROL_AC_SUCCESS: 'GET_ROL_AC_SUCCESS',
    GET_PRF_AC_SUCCESS: 'GET_PRF_AC_SUCCESS',
    GET_FICHA_USER_SUCCESS: 'GET_FICHA_USER_SUCCESS',
    GET_USRS_ACTIVOS: 'GET_USRS_ACTIVOS'
};

const TicketConstants = {
    TCKT_REQUEST: 'TCKT_REQUEST',
    TCKT_FAILURE: 'TCKT_FAILURE',
    TCKT_SUCCESS: 'TCKT_SUCCESS',
    GET_CTGR_TCKT_SUCCESS: 'GET_CTGR_TCKT_SUCCESS',
    GET_TCKT_CTGR_SUCCESS: 'GET_TCKT_CTGR_SUCCESS',
    GET_PTGS_SUCCESS: 'GET_PTGS_SUCCESS',
    GET_PTGS_ACT_SUCCESS: 'GET_PTGS_ACT_SUCCESS'
};

const DepartamentoConstants = {
    DPRT_REQUEST: 'DPRT_REQUEST',
    DPRT_FAILURE: 'DPRT_FAILURE',
    DPRT_SUCCESS: 'DPRT_SUCCESS',
    GET_DPRTS: 'GET_DPRTS',
    GET_ASGN_DPRT: 'GET_ASGN_DPRT',
    GET_DPRTS_ACTIVOS: 'GET_DPRTS_ACTIVOS'
};

export {
    UsuarioConstants,
    TicketConstants,
    DepartamentoConstants
}