-- MySQL Script generated by MySQL Workbench
-- Wed Feb 26 13:13:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbtickets
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbtickets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbtickets` DEFAULT CHARACTER SET utf8 ;
USE `dbtickets` ;

-- -----------------------------------------------------
-- Table `dbtickets`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`perfil` (
  `id_perfil` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `fecha_edit` TIMESTAMP NULL,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`rol` (
  `id_rol` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `id_rol` INT(11) NOT NULL,
  `id_perfil` INT(11) NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `token` TEXT NULL,
  `soporte` CHAR(1) NULL DEFAULT 0,
  `restablecer` CHAR(1) NULL DEFAULT '1',
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_usuario`, `id_rol`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) ,
  INDEX `fk_usuario_perfil1_idx` (`id_perfil` ASC) ,
  INDEX `fk_usuario_rol1_idx` (`id_rol` ASC) ,
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `dbtickets`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `dbtickets`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`modulo` (
  `id_modulo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`acceso` (
  `id_acceso` INT(11) NOT NULL AUTO_INCREMENT,
  `id_modulo` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_acceso`),
  INDEX `fk_acceso_modulo_idx` (`id_modulo` ASC) ,
  CONSTRAINT `fk_acceso_modulo`
    FOREIGN KEY (`id_modulo`)
    REFERENCES `dbtickets`.`modulo` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`acceso_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`acceso_perfil` (
  `id_acceso_perfil` BIGINT(11) NOT NULL,
  `id_acceso` INT(11) NOT NULL,
  `id_perfil` INT(11) NOT NULL,
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_acceso_perfil`),
  INDEX `fk_acceso_perfil_acceso1_idx` (`id_acceso` ASC) ,
  INDEX `fk_acceso_perfil_perfil1_idx` (`id_perfil` ASC) ,
  CONSTRAINT `fk_acceso_perfil_acceso1`
    FOREIGN KEY (`id_acceso`)
    REFERENCES `dbtickets`.`acceso` (`id_acceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acceso_perfil_perfil1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `dbtickets`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`acceso_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`acceso_usuario` (
  `id_acceso_usuario` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `id_acceso` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_acceso_usuario`),
  INDEX `fk_acceso_usuario_acceso1_idx` (`id_acceso` ASC) ,
  INDEX `fk_acceso_usuario_usuario1_idx` (`id_usuario` ASC) ,
  CONSTRAINT `fk_acceso_usuario_acceso1`
    FOREIGN KEY (`id_acceso`)
    REFERENCES `dbtickets`.`acceso` (`id_acceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acceso_usuario_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dbtickets`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`departamento` (
  `id_departamento` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `fecha_edit` TIMESTAMP NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`categoria` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `fecha_edit` TIMESTAMP NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`ticket` (
  `id_ticket` INT(11) NOT NULL AUTO_INCREMENT,
  `id_categoria` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `procedimiento` TEXT NULL,
  `tiempo` INT(11) NOT NULL,
  `marca_tiempo` CHAR(1) NOT NULL,
  `prioridad` CHAR(1) NOT NULL,
  `autorizacion` CHAR(1) NULL DEFAULT 0,
  `automatico` CHAR(1) NULL DEFAULT 0,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `fecha_edit` TIMESTAMP NULL,
  PRIMARY KEY (`id_ticket`),
  INDEX `fk_ticket_categoria1_idx` (`id_categoria` ASC) ,
  CONSTRAINT `fk_ticket_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `dbtickets`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`perfil_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`perfil_ticket` (
  `id_perfil_ticket` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `id_ticket` INT(11) NOT NULL,
  `id_perfil` INT(11) NOT NULL,
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_perfil_ticket`),
  INDEX `fk_perfil_ticket_ticket1_idx` (`id_ticket` ASC) ,
  INDEX `fk_perfil_ticket_perfil1_idx` (`id_perfil` ASC) ,
  CONSTRAINT `fk_perfil_ticket_ticket1`
    FOREIGN KEY (`id_ticket`)
    REFERENCES `dbtickets`.`ticket` (`id_ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfil_ticket_perfil1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `dbtickets`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`usuario_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`usuario_ticket` (
  `id_usuario_ticket` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `id_ticket` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_usuario_ticket`),
  INDEX `fk_usuario_ticket_ticket1_idx` (`id_ticket` ASC) ,
  INDEX `fk_usuario_ticket_usuario1_idx` (`id_usuario` ASC) ,
  CONSTRAINT `fk_usuario_ticket_ticket1`
    FOREIGN KEY (`id_ticket`)
    REFERENCES `dbtickets`.`ticket` (`id_ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_ticket_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dbtickets`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`ticket_realizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`ticket_realizado` (
  `id_ticket_realizado` INT(11) NOT NULL AUTO_INCREMENT,
  `id_ticket` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `id_usuario_destino` INT(11) NOT NULL,
  `id_departamento` INT(11) NULL,
  `descripcion` TEXT NULL,
  `cierre` TEXT NULL,
  `fecha` DATETIME NULL,
  `random` CHAR(1) NULL DEFAULT 0,
  `autorizado` CHAR(1) NULL DEFAULT 0,
  `no_aplica_calificacion` CHAR(1) NULL DEFAULT 0,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `fecha_edit` TIMESTAMP NULL,
  PRIMARY KEY (`id_ticket_realizado`),
  INDEX `fk_ticket_realizado_ticket1_idx` (`id_ticket` ASC) ,
  INDEX `fk_ticket_realizado_usuario1_idx` (`id_usuario` ASC) ,
  INDEX `fk_ticket_realizado_usuario2_idx` (`id_usuario_destino` ASC) ,
  INDEX `fk_ticket_realizado_departamento1_idx` (`id_departamento` ASC) ,
  CONSTRAINT `fk_ticket_realizado_ticket1`
    FOREIGN KEY (`id_ticket`)
    REFERENCES `dbtickets`.`ticket` (`id_ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_realizado_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dbtickets`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_realizado_usuario2`
    FOREIGN KEY (`id_usuario_destino`)
    REFERENCES `dbtickets`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_realizado_departamento1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `dbtickets`.`departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`fase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`fase` (
  `id_fase` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_fase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`tcket_fase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`tcket_fase` (
  `id_tcket_fase` INT(11) NOT NULL AUTO_INCREMENT,
  `id_ticket_realizado` INT(11) NOT NULL,
  `id_fase` INT(11) NOT NULL,
  `id_usuario` INT(11) NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `fecha_fin` TIMESTAMP NULL,
  PRIMARY KEY (`id_tcket_fase`),
  INDEX `fk_tcket_fase_fase1_idx` (`id_fase` ASC) ,
  INDEX `fk_tcket_fase_ticket_realizado1_idx` (`id_ticket_realizado` ASC) ,
  INDEX `fk_tcket_fase_usuario1_idx` (`id_usuario` ASC) ,
  CONSTRAINT `fk_tcket_fase_fase1`
    FOREIGN KEY (`id_fase`)
    REFERENCES `dbtickets`.`fase` (`id_fase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tcket_fase_ticket_realizado1`
    FOREIGN KEY (`id_ticket_realizado`)
    REFERENCES `dbtickets`.`ticket_realizado` (`id_ticket_realizado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tcket_fase_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dbtickets`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`mensaje` (
  `id_mensaje` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `id_ticket_realizado` INT(11) NOT NULL,
  `mensaje` TEXT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_mensaje`),
  INDEX `fk_mensaje_ticket_realizado1_idx` (`id_ticket_realizado` ASC) ,
  INDEX `fk_mensaje_usuario1_idx` (`id_usuario` ASC) ,
  CONSTRAINT `fk_mensaje_ticket_realizado1`
    FOREIGN KEY (`id_ticket_realizado`)
    REFERENCES `dbtickets`.`ticket_realizado` (`id_ticket_realizado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensaje_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dbtickets`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`notificacion` (
  `id_notificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `id_ticket_realizado` INT(11) NOT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_initl` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_notificacion`),
  INDEX `fk_notificacion_ticket_realizado1_idx` (`id_ticket_realizado` ASC) ,
  INDEX `fk_notificacion_usuario1_idx` (`id_usuario` ASC) ,
  CONSTRAINT `fk_notificacion_ticket_realizado1`
    FOREIGN KEY (`id_ticket_realizado`)
    REFERENCES `dbtickets`.`ticket_realizado` (`id_ticket_realizado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificacion_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dbtickets`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`usuario_departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`usuario_departamento` (
  `id_usuario_departamento` INT NOT NULL AUTO_INCREMENT,
  `id_departamento` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_usuario_departamento`),
  INDEX `fk_usuario_departamento_departamento1_idx` (`id_departamento` ASC) ,
  INDEX `fk_usuario_departamento_usuario1_idx` (`id_usuario` ASC) ,
  CONSTRAINT `fk_usuario_departamento_departamento1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `dbtickets`.`departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_departamento_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dbtickets`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`pregunta` (
  `id_pregunta` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` CHAR(1) NULL,
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `fecha_edit` TIMESTAMP NULL,
  PRIMARY KEY (`id_pregunta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`pregunta_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`pregunta_categoria` (
  `id_pregunta_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `id_pregunta` INT(11) NOT NULL,
  `id_categoria` INT(11) NOT NULL,
  `calificacion` DECIMAL(10,2) NOT NULL,
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_pregunta_categoria`),
  INDEX `fk_pregunta_categoria_pregunta1_idx` (`id_pregunta` ASC) ,
  INDEX `fk_pregunta_categoria_categoria1_idx` (`id_categoria` ASC) ,
  CONSTRAINT `fk_pregunta_categoria_pregunta1`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `dbtickets`.`pregunta` (`id_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pregunta_categoria_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `dbtickets`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`calificacion` (
  `id_calificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `id_ticket_realizado` INT(11) NOT NULL,
  `id_pregunta_categoria` INT(11) NOT NULL,
  `calificacion` DECIMAL(10,2) NULL DEFAULT NULL,
  `automatico` CHAR(1) NULL DEFAULT 0,
  `fecha` TIMESTAMP NULL,
  PRIMARY KEY (`id_calificacion`),
  INDEX `fk_calificacion_ticket_realizado1_idx` (`id_ticket_realizado` ASC) ,
  INDEX `fk_calificacion_pregunta_categoria1_idx` (`id_pregunta_categoria` ASC) ,
  CONSTRAINT `fk_calificacion_ticket_realizado1`
    FOREIGN KEY (`id_ticket_realizado`)
    REFERENCES `dbtickets`.`ticket_realizado` (`id_ticket_realizado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificacion_pregunta_categoria1`
    FOREIGN KEY (`id_pregunta_categoria`)
    REFERENCES `dbtickets`.`pregunta_categoria` (`id_pregunta_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`archivo` (
  `id_archivo` INT(11) NOT NULL AUTO_INCREMENT,
  `id_ticket_realizado` INT(11) NOT NULL,
  `nombre` TEXT NOT NULL,
  `ruta` TEXT NOT NULL,
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_archivo`),
  INDEX `fk_archivo_ticket_realizado1_idx` (`id_ticket_realizado` ASC) ,
  CONSTRAINT `fk_archivo_ticket_realizado1`
    FOREIGN KEY (`id_ticket_realizado`)
    REFERENCES `dbtickets`.`ticket_realizado` (`id_ticket_realizado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`historial` (
  `id_historial` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_historial`),
  INDEX `fk_historial_usuario1_idx` (`id_usuario` ASC) ,
  CONSTRAINT `fk_historial_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dbtickets`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
