-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 16:46:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbtickets
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbtickets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbtickets` DEFAULT CHARACTER SET utf8 ;
USE `dbtickets` ;

-- -----------------------------------------------------
-- Table `dbtickets`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `password` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `token` TEXT NULL,
  `soporte` CHAR(1) NULL DEFAULT 0,
  `restablecer` CHAR(1) NULL DEFAULT '1',
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`modulo` (
  `id_modulo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`perfil` (
  `id_perfil` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `fecha_edit` TIMESTAMP NULL,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`acceso` (
  `id_acceso` INT(11) NOT NULL AUTO_INCREMENT,
  `id_modulo` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_acceso`),
  INDEX `fk_acceso_modulo_idx` (`id_modulo` ASC) ,
  CONSTRAINT `fk_acceso_modulo`
    FOREIGN KEY (`id_modulo`)
    REFERENCES `dbtickets`.`modulo` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`acceso_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`acceso_perfil` (
  `id_acceso_perfil` BIGINT(11) NOT NULL,
  `id_acceso` INT(11) NOT NULL,
  `id_perfil` INT(11) NOT NULL,
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_acceso_perfil`),
  INDEX `fk_acceso_perfil_acceso1_idx` (`id_acceso` ASC) ,
  INDEX `fk_acceso_perfil_perfil1_idx` (`id_perfil` ASC) ,
  CONSTRAINT `fk_acceso_perfil_acceso1`
    FOREIGN KEY (`id_acceso`)
    REFERENCES `dbtickets`.`acceso` (`id_acceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acceso_perfil_perfil1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `dbtickets`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbtickets`.`acceso_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbtickets`.`acceso_usuario` (
  `id_acceso_usuario` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `id_acceso` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `fecha_init` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_acceso_usuario`),
  INDEX `fk_acceso_usuario_acceso1_idx` (`id_acceso` ASC) ,
  INDEX `fk_acceso_usuario_usuario1_idx` (`id_usuario` ASC) ,
  CONSTRAINT `fk_acceso_usuario_acceso1`
    FOREIGN KEY (`id_acceso`)
    REFERENCES `dbtickets`.`acceso` (`id_acceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acceso_usuario_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `dbtickets`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
